config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "items#index"
  devise_for :users
  resources :items
  # 以下のルーティングを追加 onlyでshowアクションのみに制限
  resources :users, only: :show
  post "/callback" => "linebot#callback"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  # itemは1人のユーザーに所属するそのため単数系にする！
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # userはたくさんのitemを持っているので複数形
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    #下記によってnicknameというパラメータが登録できるようになる
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # ログインしてない時にトップページへ強制的に飛ばすコード
  before_action :move_to_index, except: :index

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  #ストロングパラメータで！！！current_user.id)＝>デバイスを導入しているから使える
  def create
    Item.create(name: item_params[:name], price: item_params[:price], buy_day: item_params[:buy_day], stock_number: item_params[:stock_number], user_id: current_user.id)
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  private

  def item_params
    params.require(:item).permit(:name, :price, :buy_day, :stock_number)
  end
end

app/controllers/linebot_controller.rb
class LinebotController < ApplicationController
  require 'line/bot'  # gem 'line-bot-api'
  require 'open-uri'
  require 'kconv'
  require 'rexml/document'

  # callbackアクションのCSRFトークン認証を無効
  protect_from_forgery :except => [:callback]

  def callback
    body = request.body.read
    signature = request.env['HTTP_X_LINE_SIGNATURE']
    unless client.validate_signature(body, signature)
      return head :bad_request
    end
    events = client.parse_events_from(body)
    events.each { |event|
      case event
        # メッセージが送信された場合の対応（機能①）
      when Line::Bot::Event::Message
        case event.type
          # ユーザーからテキスト形式のメッセージが送られて来た場合
        when Line::Bot::Event::MessageType::Text
          # event.message['text']：ユーザーから送られたメッセージ
          input = event.message['text']
          url  = "https://www.drk7.jp/weather/xml/13.xml"
          xml  = open( url ).read.toutf8
          doc = REXML::Document.new(xml)
          xpath = 'weatherforecast/pref/area[4]/'
          # 当日朝のメッセージの送信の下限値は20％としているが、明日・明後日雨が降るかどうかの下限値は30％としている
          min_per = 30
          case input
            # 「明日」or「あした」というワードが含まれる場合
          when /.*(明日|あした).*/
            # info[2]：明日の天気
            per06to12 = doc.elements[xpath + 'info[2]/rainfallchance/period[2]'].text
            per12to18 = doc.elements[xpath + 'info[2]/rainfallchance/period[3]'].text
            per18to24 = doc.elements[xpath + 'info[2]/rainfallchance/period[4]'].text
            if per06to12.to_i >= min_per || per12to18.to_i >= min_per || per18to24.to_i >= min_per
              push =
                "明日の天気だよね。\n明日は雨が降りそうだよ(>_<)\n今のところ降水確率はこんな感じだよ。\n　  6〜12時　#{per06to12}％\n　12〜18時　 #{per12to18}％\n　18〜24時　#{per18to24}％\nまた明日の朝の最新の天気予報で雨が降りそうだったら教えるね！"
            else
              push =
                "明日の天気？\n明日は雨が降らない予定だよ(^^)\nまた明日の朝の最新の天気予報で雨が降りそうだったら教えるね！"
            end
          when /.*(明後日|あさって).*/
            per06to12 = doc.elements[xpath + 'info[3]/rainfallchance/period[2]l'].text
            per12to18 = doc.elements[xpath + 'info[3]/rainfallchance/period[3]l'].text
            per18to24 = doc.elements[xpath + 'info[3]/rainfallchance/period[4]l'].text
            if per06to12.to_i >= min_per || per12to18.to_i >= min_per || per18to24.to_i >= min_per
              push =
                "明後日の天気だよね。\n何かあるのかな？\n明後日は雨が降りそう…\n当日の朝に雨が降りそうだったら教えるからね！"
            else
              push =
                "明後日の天気？\n気が早いねー！何かあるのかな。\n明後日は雨は降らない予定だよ(^^)\nまた当日の朝の最新の天気予報で雨が降りそうだったら教えるからね！"
            end
          when /.*(かわいい|可愛い|カワイイ|きれい|綺麗|キレイ|素敵|ステキ|すてき|面白い|おもしろい|ありがと|すごい|スゴイ|スゴい|好き|頑張|がんば|ガンバ).*/
            push =
              "ありがとう！！！\n優しい言葉をかけてくれるあなたはとても素敵です(^^)"
          when /.*(こんにちは|こんばんは|初めまして|はじめまして|おはよう).*/
            push =
              "こんにちは。\n声をかけてくれてありがとう\n今日があなたにとっていい日になりますように(^^)"
          else
            per06to12 = doc.elements[xpath + 'info/rainfallchance/period[2]l'].text
            per12to18 = doc.elements[xpath + 'info/rainfallchance/period[3]l'].text
            per18to24 = doc.elements[xpath + 'info/rainfallchance/period[4]l'].text
            if per06to12.to_i >= min_per || per12to18.to_i >= min_per || per18to24.to_i >= min_per
              word =
                ["雨だけど元気出していこうね！",
                 "雨に負けずファイト！！",
                 "雨だけどああたの明るさでみんなを元気にしてあげて(^^)"].sample
              push =
                "今日の天気？\n今日は雨が降りそうだから傘があった方が安心だよ。\n　  6〜12時　#{per06to12}％\n　12〜18時　 #{per12to18}％\n　18〜24時　#{per18to24}％\n#{word}"
            else
              word =
                ["天気もいいから一駅歩いてみるのはどう？(^^)",
                 "今日会う人のいいところを見つけて是非その人に教えてあげて(^^)",
                 "素晴らしい一日になりますように(^^)",
                 "雨が降っちゃったらごめんね(><)"].sample
              push =
                "今日の天気？\n今日は雨は降らなさそうだよ。\n#{word}"
            end
          end
          # テキスト以外（画像等）のメッセージが送られた場合
        else
          push = "テキスト以外はわからないよ〜(；；)"
        end
        message = {
          type: 'text',
          text: push
        }
        client.reply_message(event['replyToken'], message)
        # LINEお友達追された場合（機能②）
      when Line::Bot::Event::Follow
        # 登録したユーザーのidをユーザーテーブルに格納
        line_id = event['source']['userId']
        User.create(line_id: line_id)
        # LINEお友達解除された場合（機能③）
      when Line::Bot::Event::Unfollow
        # お友達解除したユーザーのデータをユーザーテーブルから削除
        line_id = event['source']['userId']
        User.find_by(line_id: line_id).destroy
      end
    }
    head :ok
  end

  private

  def client
    @client ||= Line::Bot::Client.new { |config|
      config.channel_secret = ENV["LINE_CHANNEL_SECRET"]
      config.channel_token = ENV["LINE_CHANNEL_TOKEN"]
    }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/linebot_helper.rb
module LinebotHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/create.html.erb
<h1>ストック表に登録が完了しました</h1>
<%= link_to '⭐️みんなのストックしている物⭐️', items_path %>

app/views/items/destroy.html.erb
<h1>ストックリストから無くなりました</h1>
<%= link_to "⭐️みんなのストックしている物⭐️", items_path %>

app/views/items/edit.html.erb
<%= form_for @item, url: item_path, html: { method: :patch } do |f| %>
  <h1>ご購入商品の情報を入力</h1>
  <p>商品名：<%= f.text_field :name %></p>
  <p>ストック数：<%= f.text_field :stock_number %></>
  <p>前回の購入日：<%= f.text_field  :buy_day %></p>
  <p>今回の購入日：<%= f.date_field  :buy_day %></p>
  <span><%= time_ago_in_words(@item.updated_at) %></span>前に購入
  
  <input type="submit" value="SENT">
  
<% end %>

app/views/items/index.html.erb
<h1>⭐️みんなのストックしている物⭐️</h1>
<% if user_signed_in? %>
  <% @items.each do |item| %>
  <%# #present?メソッドでニックネイルがなければ非表示にすることができる 又ニックネームがなければI'dが出る三項演算子%>
  <p><%= item.name %>：<%= item.price %>
  
  </p>
  <% end %>
<% else %>
  <p>ログインしてください</p>
<% end %>

<%# item.user.nickname.present?の処理結果がtrueの場合は"購入者 #{item.user.nickname}"が表示され、falseの場合は"会員No.#{item.user.id}"が表示されるようになります。 %>

app/views/items/new.html.erb
<%= form_for @item, method: :post do |f| %>
  <h1>ご購入商品の情報を入力</h1>
  <p>商品名：<%= f.text_field :name %></p>
  <p>ストック数：<%= f.text_field :stock_number %></>
  <p>買った日：<%= f.date_field  :buy_day %></p>
  
  <input type="submit" value="SENT">
<% end %>

app/views/items/update.html.erb
<h1>ストック物の更新をしました</h1>
<%= link_to "⭐️みんなのストックしている物⭐️", items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoginSample4</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      <%= link_to "⭐️みんなのストックしている物⭐️", items_path %>
      <%= link_to '新しくストック物を追加', new_item_path %>
      <%= link_to '私のストック表', user_path(current_user.id) %>
      <%= link_to '管理者画面へ', "/admin" %>
    
    <% else %>
      <%= link_to "ログイン", new_user_session_path %>
      <%= link_to "新規登録", new_user_registration_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<% @user.items.each do |item| %>
<table border="1" width="50%">
<tr>
<th>ストック物</th>

<th>買った日</th>
<th>ストック数</th>
</tr>
<tr>
<td><%= item.name %></td>

<td><%= item.buy_day %>日</td>
<td><%= item.stock_number %>個:</td>
</tr>
 </table>



  
  <span><%= time_ago_in_words(item.updated_at) %></span>前に購入
 
  <%= link_to "ストック物を買ってきたから編集", edit_item_path(item.id) , method: :get %>
  <%= link_to '買う予定は今後ないのでリストから消す', item_path(item), method: :delete, data: {confirm: "削除しますか?"}  %>
    
  
<% end %>